### PR TITLE
Implement code to parse card data from JSON file

### PR DESCRIPTION
**Pull request by utilForever**
This revision includes:
- Implement code to parse card data from JSON file (#9)
  - Add libraries
    - json
    - magic_enum
  - Create classes
    - Card
    - Cards
    - CardLoader
  - Create enum classes
    - Region
    - Keyword
    - SpellSpeed
    - Rarity
    - CardType
    - CardSet
  - Add unit test code to check methods of class 'Cards'

### CODE REVIEW

**Comment by ssw03270** [comment]
LGTM. I learn a lot thanks to you :)

**Review by ssw03270 — APPROVED** [review]
LGTM. I learn a lot thanks to you :)

**Comment by plzfday** [comment]
Nothing to add

**Review by plzfday — APPROVED** [review]
Thanks for your code.

**Pull request merged**
